project:
  type: website
  output-dir: docs

website:
  title: "Katelyn K Nguyen's Portfolio"
  navbar:
    left:
      - href: Katelyn K Nguyen Portfolio.qmd
        text: Home
        
      - text: Projects
        menu:
          - href: projects-r.qmd
            text: R

          - href: math-437.qmd
            text: RStudio

          - href: projects-python.qmd
            text: Python

          - href: projects-sql.qmd
            text: SQL

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: "darkblue"
    mainfont: "sarif"

editor: visual

